# Generated by Django 6.0.1 on 2026-02-23 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_alter_scraprequest_status_actionlog_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprequest',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scraprequest',
            name='rto_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rto_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
