# Generated by Django 6.0.1 on 2026-02-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_scraprequest_agency_scraprequest_rto_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprequest',
            name='ml_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scraprequest',
            name='prediction_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
