# Generated by Django 6.0.1 on 2026-03-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_scraprequest_ml_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TWO_WHEELER', 'Two Wheeler'), ('THREE_WHEELER', 'Three Wheeler'), ('FOUR_WHEELER', 'Four Wheeler')], max_length=50),
        ),
    ]
