# Generated by Django 6.0.1 on 2026-03-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_scraprequest_payment_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprequest',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
